version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
      - ~/.gitconfig:/.gitconfig
      - ~/.ssh:/.ssh

volumes:
  node_modules:
